name: Generate Snake Animation

on:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate the Snake
        uses: Platane/snk@v2
        with:
          github_user_name: Ritikkumar23
          outputs: dist/snake.svg

      - name: Upload Snake SVG
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
