name: Generate Snake Animation
on:
  schedule:
    # Runs every day at midnight
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Generate the snake animation
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: github-contribution-grid-snake.svg

      # Commit the animation file to your repository
      - name: Commit and push the animation
        run: |
          git config --global user.name "Ritikkumar23"
          git config --global user.email "ritik23.kr@gmail.com"
          git add github-contribution-grid-snake.svg
          git commit -m "Generated snake animation"
          git push
