name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs once a day at midnight (UTC)
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate the snake animation
        uses: Platane/snk@v3.0.0
        with:
          github_user_name: Ritikkumar23
          outputs: dist/snake.svg

      - name: Upload the snake animation
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/snake.svg
