name: Generate Snake Animation

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Runs the workflow daily
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Step 2: Generate the Snake SVG
      - name: Generate the Snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: RitikKumar23
          outputs: dist/snake.svg

      # Step 3: Publish the Snake SVG to GitHub Pages
      - name: Upload the Snake animation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
